config/routes.rb
Rails.application.routes.draw do
  get 'contact/new'
  post 'contact/create'
  get 'home/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root to: "home#index"
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  resources :shopping_carts, only: [:show, :update, :destroy] do
    member do
      post :pay_with_paypal
      get :process_paypal_payment
    end
  end

  resources :payment
  resources :orders
  resources :products
  resources :categories
  post '/rate' => 'rater#create', :as => 'rate'
  post '/' => 'home#create', :as => 'home_create'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
        :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true



  
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, presence: {message: "Debe ingresar nombre de la categoria"}
  def to_s
    name
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :shopping_carts, dependent: :destroy
  has_many :products, through: :shopping_carts, dependent: :destroy
  has_many :payments


  def to_s
    email  
  end

  def add_product(product_id, quantity) 
    product = Product.find(product_id)
    bag = self.shopping_carts.find_by_product_id(product.id)
    if product && (product.stock > 0)
      if bag.nil?
        shopping_carts.create(product_id: product.id, quantity: quantity, price: product.price )
      else
        bag.update_attribute(:quantity, bag.quantity + 1)
      end
      total_amount
    end 
  end

#metodo para sumar en el total del carrito
  def total_amount
    subtotal = 0
    self.shopping_carts.map do |product|
      subtotal += product.price * product.quantity
    end
    update_attribute(:total, subtotal)
  end
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
  belongs_to :payment_method
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
  has_many :payments
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :shopping_carts, dependent: :destroy
  has_many :orders, through: :shopping_carts, dependent: :destroy
  validates :name, presence: {message: "Debe ingresar nombre del producto"}
  validates :sku, presence: {message: "Debe ingresar SKU del producto"}
  validates :description, presence: {message: "Debe ingresar descripción del producto"}
  validates :stock, presence: {message: "Debe ingresar stock del producto"}
  validates :price, presence: {message: "Debe ingresar precio del producto"}
  validates :pictures, presence: {message: "Debe ingresar imagen del producto"}
  validates :category, presence: {message: "Debe seleccionar categoria del producto"}
  belongs_to :category, optional: {message: "Debe seleccionar categoria del producto"}
  ratyrate_rateable "price"
  has_many_attached :pictures

  def to_s
    name
  end



end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  belongs_to :order
  belongs_to :product



  def new_total_order
    self.order.update_attribute(:total, self.order.total - self.price) 
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable,
          :omniauthable, omniauth_providers: %i[github google_oauth2 facebook]
  validates :name, :lastname, :email, :rut, :address, presence: true
  
  ratyrate_rater

  def self.from_omniauth(auth)
    user = User.find_by(email: auth.info.email)
    if user
      user.provider = auth.provider
      user.uid = auth.uid
      user.save
    else
      user = User.where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end
    end
    user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  
  def index
  end

end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_cart , only: %i[destroy] 
  
  
  def update
    product = params[:shopping_cart][:product_id]
    quantity = params[:shopping_cart][:quantity]
    current_order.add_product(product, quantity)
    redirect_to shopping_cart_path, notice: 'Producto Agregado con éxito!'
  end
  
  def show
    @order = current_order
  end

  
  def destroy
    @cart.order.total = @cart.new_total_order
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to shopping_cart_url, notice: 'Se borro tu producto del carrito.' }
      format.json { head :no_content }
    end
  end


  def pay_with_paypal

    order = Order.find(params[:shopping_cart][:order_id])
    price = order.total

    response = EXPRESS_GATEWAY.setup_purchase(price, ip: request.remote_ip,
    return_url: process_paypal_payment_shopping_cart_url,
    cancel_return_url: root_url,
    
    allow_guest_checkout: true,
    currency: 'USD' )
    payment_method = PaymentMethod.find_by(code: 'PEC')

    Payment.create(
    order_id: order.id, payment_method_id: payment_method.id, status: 'processing',
    total: order.total,
    token: response.token
    )
    redirect_to EXPRESS_GATEWAY.redirect_url_for(response.token)
  end

  def process_paypal_payment
    details = EXPRESS_GATEWAY.details_for(params[:token]) 
    express_purchase_options =
    {
      ip: request.remote_ip, token: params[:token], 
      payer_id: details.payer_id, 
      currency: 'USD'
        }
    price = details.params['order_total'].to_d
    response = EXPRESS_GATEWAY.purchase(price, express_purchase_options) 
      if response.success?
        payment = Payment.find_by(token: response.token) 
        order = payment.order
        payment.status = 'completed'
        order.status = 'completed'
        ActiveRecord::Base.transaction do 
          order.save!
          payment.save!
          end
        redirect_to root_path, notice: 'Compra exitosa'
        else
          redirect_to root_path, notice: 'Hemos tenido problemas para procesar tu pago'
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def find_cart
      @cart = ShoppingCart.find(params[:id])
    end

    def cart_params
      params.require(:shopping_cart).permit(:quantity, :order_id, :product_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

app/views/shopping_carts/_form.html.erb
<%= form_with(model: shopping_cart, local: true) do |form| %>
  <% if shopping_cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shopping_cart.errors.count, "error") %> prohibited this shopping_cart from being saved:</h2>

      <ul>
      <% shopping_cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :order_id %>
    <%= form.text_field :order_id %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shopping_carts/edit.html.erb
<h1>Editing Shopping Cart</h1>

<%= render 'form', shopping_cart: @shopping_cart %>

<%= link_to 'Show', @shopping_cart %> |
<%= link_to 'Back', shopping_carts_path%>

app/views/shopping_carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shopping Carts</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Product</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shopping_carts.each do |shopping_cart| %>
      <tr>
        <td><%= shopping_cart.order %></td>
        <td><%= shopping_cart.product %></td>
        <td><%= shopping_cart.quantity %></td>
        <td><%= link_to 'Show', shopping_cart %></td>
        <td><%= link_to 'Edit', edit_shopping_cart_path(shopping_cart) %></td>
        <td><%= link_to 'Destroy', shopping_cart, method: :delete, data: { confirm: '¿Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shopping Cart', new_shopping_cart_path %>

app/views/shopping_carts/new.html.erb
<h1>New Shopping Cart</h1>

<%= render 'form', shopping_cart: @shopping_cart %>

<%= link_to 'Back', shopping_carts_path %>

app/views/shopping_carts/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <div class="card">
    <div class="card-header text-light">
        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
        <a href="<%= products_path%>" class="btn btn-outline-info btn-sm pull-right">Continua Comprando</a>
        <div class="clearfix">
      </div> 
  </div>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Foto</th>
        <th scope="col">Nombre</th>
        <th scope="col">Precio Unitario</th>
        <th scope="col">Cantidad</th>
        <th scope="col">Subtotal</th>
      </tr>
    </thead>
    <tbody>   
      <% @order.shopping_carts.includes(:product).each do |item| %>      
        <tr>
          <td> 
            <%= image_tag item.product.pictures.last.variant(resize: "80x80"), class:"img-responsive" %>
          </td>
          <td>  
            <h4 class="product-name"><strong><%= item.product.name %></strong></h4>
          </td>  
          <td>   
          $<%= item.product.price%>
          </td>
          <td>
            <%= item.quantity %>
          </td>
          <td>      
            $<%= item.quantity * item.price %>
          </td>
          <td>          
            <%= link_to shopping_cart_path(item), method: :delete, data: { confirm: '¿Estas seguro?' } do %>
            <i class="fas fa-trash-alt"></i> 
            <% end %>
          </td>
            <% end %>
      </tbody>
  </table>
      <div class="card-footer">
        <div class="pull-right" style="margin: 5px">Total: $<%= @order.total%> 
          <%= form_for :shopping_cart, url: pay_with_paypal_shopping_cart_path, method: :post do |f|%>
            <%= f.hidden_field :order_id, value: @order.id %>
            <%= f.submit 'Pagar' %>
          <% end %>
        </div> 
      </div> 
</div>