config/routes.rb
Rails.application.routes.draw do
  get 'contact/new'
  post 'contact/create'
  get 'home/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root to: "home#index"
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  resources :shopping_carts, only: [:show, :update, :destroy] do
    member do
      post :pay_with_paypal
      get :process_paypal_payment
    end
  end

  resources :payment
  resources :orders
  resources :products
  resources :categories
  post '/rate' => 'rater#create', :as => 'rate'
  post '/' => 'home#create', :as => 'home_create'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
        :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true



  
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, presence: {message: "Debe ingresar nombre de la categoria"}
  def to_s
    name
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :shopping_carts, dependent: :destroy
  has_many :products, through: :shopping_carts, dependent: :destroy
  has_many :payments


  def to_s
    email  
  end

  def add_product(product_id, quantity) 
    product = Product.find(product_id)
    bag = self.shopping_carts.find_by_product_id(product.id)
    if product && (product.stock > 0)
      if bag.nil?
        shopping_carts.create(product_id: product.id, quantity: quantity, price: product.price )
      else
        bag.update_attribute(:quantity, bag.quantity + 1)
      end
      total_amount
    end 
  end

#metodo para sumar en el total del carrito
  def total_amount
    subtotal = 0
    self.shopping_carts.map do |product|
      subtotal += product.price * product.quantity
    end
    update_attribute(:total, subtotal)
  end
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
  belongs_to :payment_method
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
  has_many :payments
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :shopping_carts, dependent: :destroy
  has_many :orders, through: :shopping_carts, dependent: :destroy
  validates :name, presence: {message: "Debe ingresar nombre del producto"}
  validates :sku, presence: {message: "Debe ingresar SKU del producto"}
  validates :description, presence: {message: "Debe ingresar descripción del producto"}
  validates :stock, presence: {message: "Debe ingresar stock del producto"}
  validates :price, presence: {message: "Debe ingresar precio del producto"}
  validates :pictures, presence: {message: "Debe ingresar imagen del producto"}
  validates :category, presence: {message: "Debe seleccionar categoria del producto"}
  belongs_to :category, optional: {message: "Debe seleccionar categoria del producto"}
  ratyrate_rateable "price"
  has_many_attached :pictures

  def to_s
    name
  end



end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  belongs_to :order
  belongs_to :product



  def new_total_order
    self.order.update_attribute(:total, self.order.total - self.price) 
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable,
          :omniauthable, omniauth_providers: %i[github google_oauth2 facebook]
  validates :name, :lastname, :email, :rut, :address, presence: true
  
  ratyrate_rater

  def self.from_omniauth(auth)
    user = User.find_by(email: auth.info.email)
    if user
      user.provider = auth.provider
      user.uid = auth.uid
      user.save
    else
      user = User.where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end
    end
    user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html lang="es">
    <head>
      <title>Kimera Accessories</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
      <meta name="Author" content="Ender Ruiz" />
      <link rel="shortcut icon" type="image/png" href="assets/logo_kimera.png" sizes="60x60">
      <link rel="stylesheet" href="../../assets/stylesheets/main.css" />
      <noscript><link rel="stylesheet" href="assets/stylesheets/noscript.css" /></noscript>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.css" crossorigin="anonymous">
      <link rel="preconnect" href="https://fonts.gstatic.com">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" />
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    </head>

    <body class="is-preload">
        <%= render 'shared/navbar' %>
            <%= yield %>
        <%= render 'shared/footer' %>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.js" crossorigin="anonymous"></script>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </body>
</html>

app/views/shared/_footer.html.erb
<footer id="footer" class="fixed-bottom">
	<ul class="icons">
		<h3>Síguenos:</h2>
			<a href="http://wa.link/o16a2f/" class="icon brands fa-whatsapp"> <span class="label">Whatsapp</span></a></li>
			<li><a href="https://www.facebook.com/kimeraaccesorioscl" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
			<li><a href="https://instagram.com/kimera_accesorios?utm_medium=copy_link" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
						<li><p class="label">Kimera Accesorios, domiciliada en Avenida , Manquehue Norte 151 Of 908 Ps 9 Comuna Las Condes Region Metropolitana.<br>Precios publicados aplican exclusivamente a Internet y Venta Telefónica. Telefono: 22602d2233</p></li>
			</ul>
      <h3 class="font-weight-bold text-center">Ahora aceptamos</h3>
          <i class="fab fa-cc-mastercard p-2"></i>
          <i class="fab fa-cc-visa p-2" ></i>
          <i class="fab fa-cc-paypal p-2"></i>
					</div>
		</footer>

app/views/shared/_navbar.html.erb
<header id="header">
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
        <a class="navbar-brand cuadro" href="<%= root_path %>"> 
          <%= image_tag("logo_kimera.jpeg", class:'logo') %> 
        </a> 
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ml-auto">
              <ul>
                <li><%= link_to 'Productos', products_path%><li>
                  <% if current_user %>
                <li><%= link_to 'Ordenes', orders_path%></li>
                <li class="nav-item">
                    <% if @order.present?  %>
                        <%= link_to (shopping_cart_path(@order)) do %>
                          <i class="fas fa-shopping-cart text-secundary fa-2x mx-2"></i>
                        <% end %>
                    <% end %>
                </li>
                <li>
                  <%# ---- aqui empieza el dropdown %>
                  <div class="dropdown ml-auto">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-expanded="false">
                      <%= current_user ? current_user.name : 'Ingresar'%>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                        <%= link_to 'Editar Perfil', edit_user_registration_path, class:'dropdown-item' %>
                        <%= link_to 'Salir', destroy_user_session_path, method: :delete, class:'dropdown-item' %>
                    </div>
                  </div>
                </li>
                  <% else  %>
                <li><%= link_to 'Registrate Aqui', new_user_registration_path, class:'btn btn-warning mx-2 nav-item' %></li>
                <li><%= link_to 'Inicia Sesion', new_user_session_path, class:'btn btn-light mx-2 nav-item'  %></li>
                  <% end %>
              </ul>
            </div>
          </div>
  </nav>
</header>

app/views/shared/_subnavbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light subnavbar">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto mr-auto">
      <li class="nav-item">
        <a href='#one' class="nav-link">¿Quienes somos?</a>
      </li>
      <li class="nav-item">
        <a href='#two' class="nav-link">Nueva Colección</a>
      </li>
      <li class="nav-item">
        <a href='#work' class="nav-link">Categorias</a>
      </li>
            <li class="nav-item">
        <a href='#contact' class="nav-link">Contáctanos</a>
      </li>
    </ul>
  </div>
</nav>