config/routes.rb
Rails.application.routes.draw do
  get 'contact/new'
  post 'contact/create'
  get 'home/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root to: "home#index"
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  resources :shopping_carts, only: [:show, :update, :destroy] do
    member do
      post :pay_with_paypal
      get :process_paypal_payment
    end
  end

  resources :payment
  resources :orders
  resources :products
  resources :categories
  post '/rate' => 'rater#create', :as => 'rate'
  post '/' => 'home#create', :as => 'home_create'
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :shopping_carts, dependent: :destroy
  has_many :orders, through: :shopping_carts, dependent: :destroy
  validates :name, presence: {message: "Debe ingresar nombre del producto"}
  validates :sku, presence: {message: "Debe ingresar SKU del producto"}
  validates :description, presence: {message: "Debe ingresar descripción del producto"}
  validates :stock, presence: {message: "Debe ingresar stock del producto"}
  validates :price, presence: {message: "Debe ingresar precio del producto"}
  validates :pictures, presence: {message: "Debe ingresar imagen del producto"}
  validates :category, presence: {message: "Debe seleccionar categoria del producto"}
  belongs_to :category, optional: {message: "Debe seleccionar categoria del producto"}
  ratyrate_rateable "price"
  has_many_attached :pictures

  def to_s
    name
  end



end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :crud_to_admin, only: %i[ new create edit update destroy ]
  
  
  # GET /products or /products.json
  def index 
    @products = Product.all.order(created_at: :asc)
    if current_user
      @order = Order.find_by(user_id: current_user.id)
    end

    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true)

    @products = Kaminari.paginate_array(@products).page(params[:page]).per(6)
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    @categories = Category.all
    params.require(:product).permit(:name, :description, :stock, images: [])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :sku, :description, :stock, :photo, :category_id, :price, pictures: [])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="container">

  <%= form_with(model: product, local: true) do |form| %>
    <% if product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :Nombre %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :sku %>
      <%= form.text_field :sku %>
    </div>

    <div class="field">
      <%= form.label :Descripción %>
      <%= form.text_area :descriptions %>
    </div>


    <div class="field">
      <%= form.label :Fotos %>
      <%= form.file_field :pictures, multiple: true %>
    </div>

    <div class="field">
      <%= form.label :Stock %>
      <%= form.number_field :stock %>
    </div>

    <div class="field">
      <%= form.label :Precio %>
      <%= form.number_field :price %>
    </div>

    <div class="field">
      <%= form.label :Categoria %>
        <%= form.collection_select :category_id, @categories, :id, :name %> 
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="container">

    <%= search_form_for @q do |f|%>
        <div class="ml-auto">
            <% if current_user && current_user.admin == true  %>
            <%= link_to 'Nuevo Producto', new_product_path, class:'btn btn-outline-success btn-light mx-2' %>
            <%= link_to 'Nueva Categoria', new_category_path, class:'btn btn-outline-success btn-light' %>
            <% end  %>
        </div>
        <div  class="form-inline my-2 my-lg-0"%>
            <%= f.search_field :name_or_description_cont, placeholder: 'Buscar Productos', class:"form-control mr-sm-2" %>
            <%= f.submit "Buscar", class:"form-control btn-outline-success mx-2 my-2" %> 
            <%= link_to "Mostrar todos", products_path, class:'form-control btn btn-light text-black'%>
        </div>
    <% end %>

    <div class="row">
            <div class="card-deck container-fluid border-solid py-2 mx-auto">
            <% @products.each do |product| %>
                <div class="col-4 my-2">
                    <div class="card" style="width: 18rem;">
                            <%= link_to product_path(product) do%>
                                <%= image_tag product.pictures.last.variant(resize: "250x250"), class:"card-img-top photocard" %>
                            <% end  %>
                            <h1 class="card-title text-center"><%= product.name %></h1>
                            <span class="badge badge-pill text-left badge-light">Categoria: <%= product.category %></span>
                            <%= form_for :shopping_cart, url: shopping_cart_path(product), method: :put do |f| %>
                            <%= f.hidden_field :product_id, value: product.id %>
                            <%= f.hidden_field :quantity, value: 1 %>
                            <span>Calificación : <%= rating_for product, 'price', star: 5 %></span>
                            <p class="card-text h4 text-danger">Precio $<%= product.price %></p>
                            <%= f.submit "Agregar al carrito", class:"btn-sm mx-2 my-2"%>
                    </div>
                </div>
                <% end %>
            <% end %>
        </div>
    </div>
        <%= paginate @products %>
</div>

app/views/products/new.html.erb
<div class=container>
<h1>Nuevo Producto</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path, class:"btn btn-outline-success" %>
</div>

app/views/products/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="media border border-success mb-4">
      <% @product.pictures.each do |picture| %>
        <%= image_tag picture.variant(resize: "600x600"), class:"align-self-center mx-4 border border-success" %>
      <% end  %>
      <div class="media-body">
        <h2 class="mt-0"><%= @product.name %></h2>
          <strong> SKU:</strong>
            <p><%= @product.sku %></p>
          <strong>Descripción:</strong>
            <p><%= @product.description %> </p>
          <strong>Stock:</strong>
            <p>Quedan <%= @product.stock %> Unid.</p>
          <strong>Categoria:</strong>
            <p><%= @product.category %></p>
          <strong>Precio:</strong>
            <p><%= @product.price %></p>
            <p>Calidad  : <%= rating_for @product, 'price', star: 5 %> </p>
            <% if current_user && current_user.admin == true %>
              <%= link_to edit_product_path(@product) do %> 
                <i class="fas fa-edit fa-2x"></i>
                  <% end %>
              <%= link_to products_path do %>  
                <i class="fas fa-arrow-circle-left fa-2x"></i>
                  <% end %>  
              <%= link_to @product, method: :delete, data: { confirm: '¿Estas seguro?' } do %>
                <i class="fas fa-trash-alt fa-2x"></i>
                  <% end %>
        </div>
        <% end %>
    </div>
</div>